version: '3.8'

services:
  solr:
    image: solr:9.4
    container_name: nas-search-solr
    ports:
      - "${SOLR_PORT:-8983}:8983"
    volumes:
      - ./solr/configsets:/opt/solr/server/solr/configsets
      - ${NAS_SEARCH_DATA_DIR:-./nas-search-data}/solr:/var/solr
      - ${NAS_SEARCH_DATA_DIR:-./nas-search-data}/logs:/var/log/solr
    environment:
      - SOLR_HEAP=${SOLR_HEAP:-2g}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    command: >
      bash -c "
        solr-precreate nas_content /opt/solr/server/solr/configsets/nas_content &&
        exec solr -f
      "
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: nas-search-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - ${NAS_SEARCH_DATA_DIR:-./nas-search-data}/redis:/data
      - ${NAS_SEARCH_DATA_DIR:-./nas-search-data}/logs:/var/log/redis
    command: redis-server --appendonly ${REDIS_PERSISTENCE:-yes}
    restart: unless-stopped

  file-monitor:
    build:
      context: ./services/file-monitor
      dockerfile: Dockerfile
    container_name: nas-search-file-monitor
    volumes:
      - ${NAS_PATH:-./test-data}:/nas:ro
      - ${NAS_SEARCH_DATA_DIR:-./nas-search-data}/logs:/var/log/app
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - NAS_PATH=/nas
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    depends_on:
      - redis
    restart: unless-stopped

  metadata-extractor:
    build:
      context: ./services/metadata-extractor
      dockerfile: Dockerfile
    container_name: nas-search-metadata-extractor
    volumes:
      - ${NAS_PATH:-./test-data}:/nas:ro
      - ${NAS_SEARCH_DATA_DIR:-./nas-search-data}/logs:/var/log/app
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - SOLR_URL=${SOLR_URL:-http://solr:8983/solr/nas_content}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    depends_on:
      - redis
      - solr
    restart: unless-stopped

  thumbnail-generator:
    build:
      context: ./services/thumbnail-generator
      dockerfile: Dockerfile
    container_name: nas-search-thumbnail-generator
    volumes:
      - ${NAS_PATH:-./test-data}:/nas:ro
      - ${NAS_SEARCH_DATA_DIR:-./nas-search-data}/thumbnails:/app/thumbnails
      - ${NAS_SEARCH_DATA_DIR:-./nas-search-data}/logs:/var/log/app
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - THUMBNAIL_DIR=/app/thumbnails
      - THUMBNAIL_QUALITY=${THUMBNAIL_QUALITY:-85}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    depends_on:
      - redis
    restart: unless-stopped

  nas-search-app:
    build:
      context: ./nas-search-app
      dockerfile: Dockerfile
    container_name: nas-search-app
    ports:
      - "${APP_PORT:-3000}:3000"
    volumes:
      - ${NAS_SEARCH_DATA_DIR:-./nas-search-data}/thumbnails:/app/thumbnails
      - ${NAS_SEARCH_DATA_DIR:-./nas-search-data}/logs:/var/log/app
    environment:
      - SOLR_URL=${SOLR_URL:-http://solr:8983/solr/nas_content}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - THUMBNAIL_DIR=/app/thumbnails
      - NAS_SEARCH_DATA_DIR=/data
      - ENABLE_DISK_MONITORING=${ENABLE_DISK_MONITORING:-true}
      - DISK_WARNING_THRESHOLD=${DISK_WARNING_THRESHOLD:-80}
      - DISK_CRITICAL_THRESHOLD=${DISK_CRITICAL_THRESHOLD:-90}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    depends_on:
      - solr
      - redis
    restart: unless-stopped

# Remove volume definitions since we're using host mounts
networks:
  default:
    name: nas-search-network